---
- hosts: localhost
  gather_facts: true
  vars_files:
    - inventory/group_vars/all.yml

  roles:
    - role: tools/kubectl
    - role: tools/helm
    - role: tools/k9s
    - role: k3s
      when: k8s_distro == "k3s"
    - role: rke2
      when: k8s_distro == "rke2"
    - role: ingress-nginx
      when: disable_traefik == "true"
    - role: k8s-tools/cert-manager
    - role: k8s-tools/rancher
    - role: k8s-tools/wildcard-cert