- name: Cluster preparation
  hosts: k3s_cluster
  gather_facts: true
  become: true
  vars_files:
    - inventory/group_vars/all.yml

  roles:
    - role: prereq
      when: k8s_distro == "k3s"
    - role: airgap
      when: k8s_distro == "k3s"
    - role: raspberrypi
      when: k8s_distro == "k3s" and "'raspberrypi' in ansible_facts['devices']"

- name: Setup K3S server
  hosts: server
  gather_facts: true
  become: true
  roles:
    - role: k3s-ansible.k3s_server
      when: k8s_distro == "k3s"

- name: Setup K3S agent
  hosts: agent
  gather_facts: true
  become: true
  roles:
    - role: k3s-ansible.k3s_agent
      when: k8s_distro == "k3s"

- name: Deploy Kubernetes tools
  hosts: all
  gather_facts: true
  vars_files:
    - inventory/group_vars/all.yml

  roles:
    - role: tools/kubectl
    - role: tools/helm
    - role: tools/k9s
    - role: k8s-tools/ingress-nginx
      when: disable_traefik == "true" and k8s_distro == "k3s"
    - role: k8s-tools/cert-manager
    - role: k8s-tools/rancher
      when: rancher_install == "true"
    - role: k8s-tools/wildcard-cert
      when: wildcard_cert == "true"
    - role: k8s-tools/reflector
      when: reflector == "true"

- name: Run additional tasks
  hosts: all
  gather_facts: true
  tags: test
  roles:
    - role: k8s-tools/test-nginx
      when: "'test' in ansible_run_tags"

- name: Cleanup tasks
  hosts: all
  gather_facts: true
  tags: cleanup
  roles:
    - role: cleanup
      when: "'cleanup' in ansible_run_tags"