---
- name: Install RKE2
  shell: |
    curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION={{ rke2_version }} sh -s -
  register: rke2_install_result
  changed_when: rke2_install_result.rc == 0

- name: Ensure RKE2 config directory exists
  file:
    path: /etc/rancher/rke2
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Create RKE2 config file
  template:
    src: config.yaml.j2
    dest: /etc/rancher/rke2/config.yaml
    owner: root
    group: root
    mode: '0644'

- name: Restart RKE2 service to apply configuration
  systemd:
    name: rke2-server
    state: restarted

- name: Ensure $HOME/.kube directory exists
  file:
    path: "{{ lookup('env', 'HOME') }}/.kube"
    state: directory
    mode: '0700'

- name: Copy kubeconfig to desired location
  copy:
    src: "{{ rke2_kubeconfig_path | default('/etc/rancher/rke2/rke2.yaml') }}"
    dest: "{{ lookup('env', 'HOME') }}/.kube/config"
    remote_src: true
    mode: '0600'
  become: true

- name: Update server IP in kubeconfig
  replace:
    path: "{{ lookup('env', 'HOME') }}/.kube/config"
    regexp: '127.0.0.1'
    replace: "{{ tls_sans.split(',')[0] }}"

- name: Sleep for 30 seconds to allow RKE2 to fully initialize
  wait_for:
    timeout: 30
